TestOrganization/Models/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace TestOrganization.Models
{
    public class Employee
    {
        [Key]
        public string Id { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        public string Address { get; set; }

        public string Designation { get; set; }

        public string OrganizationId { get; set; }

        public string? ReportsTo { get; set; }
    }
}

TestOrganization/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TestOrganization.Data;
using TestOrganization.Models;
using TestOrganization.Models.DTO;

namespace TestOrganization.Controllers
{
    [Authorize]
    public class EmployeesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmployeesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index(string id)
        {
            ViewBag.Id = id;
            return View(await _context.Employees.Where(x => x.OrganizationId == id).ToListAsync());
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            var Oid = _context.Employees.Where(x => x.Id == id).Select(x => x.OrganizationId).FirstOrDefault();
            if (employee == null)
            {
                return NotFound();
            }
            ViewBag.Id = Oid;
            return View(employee);
        }

        // GET: Employees/Create
        public async Task<IActionResult> Create(string id)
        {
            var organization = _context.Organizations.Find(id);
            var emp = new EmployeeDTO
            {
                OrganizationId = organization.Id,
            };
            var deg = await _context.Designations.ToListAsync();
            ViewBag.Designation = deg;
            return View(emp);
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string id, EmployeeDTO employeeDTO)
        {
            if (ModelState.IsValid)
            {
                var employee = new Employee
                {
                    Id = Guid.NewGuid().ToString(),
                    FirstName = employeeDTO.FirstName,
                    LastName = employeeDTO.LastName,
                    Address = employeeDTO.Address,
                    OrganizationId = id,
                    Designation = employeeDTO.Designation
                };
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Employees", new { id = id });
            }
            return View(employeeDTO);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            var Oid = _context.Employees.Where(x => x.Id == id).Select(x => x.OrganizationId).FirstOrDefault();
            var emp = new EmployeeEditDTO
            {
                Id = employee.Id,
                FirstName = employee.FirstName,
                LastName = employee.LastName,
                Address = employee.Address,
                Designation = employee.Designation,
                ReportsTo = employee.ReportsTo
            };
            if (emp == null)
            {
                return NotFound();
            }
            ViewBag.Id = Oid;
            var deg = await _context.Designations.ToListAsync();
            ViewBag.Designation = deg;
            var developer = await _context.Designations.Where(x => x.Name == "Developer").FirstAsync();
            var teamLead = await _context.Designations.Where(x => x.Name == "Team Lead").FirstAsync();
            var projectManager = await _context.Designations.Where(x => x.Name == "Project Manager").FirstAsync();

            var rtsTo = new List<Employee>();
            if (employee.Designation == developer.Name)
            {
                rtsTo = await _context.Employees.Where(x => x.Designation == teamLead.Id && x.OrganizationId == Oid).Select(x => x).ToListAsync();
            }
            else if (employee.Designation == teamLead.Name)
            {
                rtsTo = await _context.Employees.Where(x => x.Designation == projectManager.Id && x.OrganizationId == Oid).Select(x => x).ToListAsync();
            }
            else
            {
                rtsTo = await _context.Employees.Where(x => x.Id == null).ToListAsync();
            }
            ViewBag.rtsTo = rtsTo;
            return View(emp);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,FirstName,LastName,Address,Designation,ReportsTo")] EmployeeEditDTO eeDTO)
        {
            if (id != eeDTO.Id)
            {
                return NotFound();
            }
            var Oid = _context.Employees.Where(x => x.Id == id).Select(x => x.OrganizationId).FirstOrDefault();
            if (ModelState.IsValid)
            {
                try
                {
                    var employee = new Employee
                    {
                        Id = id,
                        FirstName = eeDTO.FirstName,
                        LastName = eeDTO.LastName,
                        Address = eeDTO.Address,
                        OrganizationId = Oid,
                        Designation = eeDTO.Designation,
                        ReportsTo = eeDTO.ReportsTo
                    };
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(eeDTO.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { id = Oid });
            }
            return View(eeDTO);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            var Oid = _context.Employees.Where(x => x.Id == id).Select(x => x.OrganizationId).FirstOrDefault();
            if (employee == null)
            {
                return NotFound();
            }
            ViewBag.Id = Oid;
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Employees == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Employees'  is null.");
            }
            var employee = await _context.Employees.FindAsync(id);
            var Oid = _context.Employees.Where(x => x.Id == id).Select(x => x.OrganizationId).FirstOrDefault();
            if (employee != null)
            {
                _context.Employees.Remove(employee);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { id = Oid });
        }

        private bool EmployeeExists(string id)
        {
          return (_context.Employees?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

TestOrganization/Controllers/LeaveRequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestOrganization.Data;
using TestOrganization.Models;

namespace TestOrganization.Controllers
{
    public class LeaveRequestsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LeaveRequestsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: LeaveRequests
        public async Task<IActionResult> Index()
        {
              return _context.LeaveRequests != null ? 
                          View(await _context.LeaveRequests.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.LeaveRequests'  is null.");
        }

        // GET: LeaveRequests/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.LeaveRequests == null)
            {
                return NotFound();
            }

            var leaveRequest = await _context.LeaveRequests
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (leaveRequest == null)
            {
                return NotFound();
            }

            return View(leaveRequest);
        }

        // GET: LeaveRequests/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: LeaveRequests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmployeeId,Message,LeaveDate,ReturnDate")] LeaveRequest leaveRequest)
        {
            if (ModelState.IsValid)
            {
                _context.Add(leaveRequest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(leaveRequest);
        }

        // GET: LeaveRequests/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.LeaveRequests == null)
            {
                return NotFound();
            }

            var leaveRequest = await _context.LeaveRequests.FindAsync(id);
            if (leaveRequest == null)
            {
                return NotFound();
            }
            return View(leaveRequest);
        }

        // POST: LeaveRequests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("EmployeeId,Message,LeaveDate,ReturnDate")] LeaveRequest leaveRequest)
        {
            if (id != leaveRequest.EmployeeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(leaveRequest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeaveRequestExists(leaveRequest.EmployeeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(leaveRequest);
        }

        // GET: LeaveRequests/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.LeaveRequests == null)
            {
                return NotFound();
            }

            var leaveRequest = await _context.LeaveRequests
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (leaveRequest == null)
            {
                return NotFound();
            }

            return View(leaveRequest);
        }

        // POST: LeaveRequests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.LeaveRequests == null)
            {
                return Problem("Entity set 'ApplicationDbContext.LeaveRequests'  is null.");
            }
            var leaveRequest = await _context.LeaveRequests.FindAsync(id);
            if (leaveRequest != null)
            {
                _context.LeaveRequests.Remove(leaveRequest);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LeaveRequestExists(string id)
        {
          return (_context.LeaveRequests?.Any(e => e.EmployeeId == id)).GetValueOrDefault();
        }
    }
}

TestOrganization/Views/Employees/Create.cshtml
@model TestOrganization.Models.DTO.EmployeeDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrganizationId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Designation" class="control-label"></label>
                <select asp-for="Designation" class ="form-control" >
                    <option value = ""> -- choose -- </option>
                    @foreach (var item in ViewBag.Designation)
                    {
                        <option value = "@item.Name">@item.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestOrganization/Views/Employees/Delete.cshtml
@model TestOrganization.Models.Employee

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" asp-route-id="@ViewBag.Id">Back to List</a>
    </form>
</div>

TestOrganization/Views/Employees/Details.cshtml
@model TestOrganization.Models.Employee

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index" asp-route-id="@ViewBag.Id">Back to List</a>
</div>

TestOrganization/Views/Employees/Edit.cshtml
@model TestOrganization.Models.DTO.EmployeeEditDTO

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Designation" class="control-label"></label>
                <select asp-for="Designation" class ="form-control" >
                    <option value = ""> -- choose -- </option>
                    @foreach (var item in ViewBag.Designation)
                    {
                        <option value = "@item.Name">@item.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ReportsTo" class="control-label"></label>
                <select asp-for="ReportsTo" class ="form-control" >
                    <option value = ""> -- choose -- </option>
                    @foreach (var item in ViewBag.rtsTo)
                    {
                        <option value = "@item.FirstName @item.LastName">@item.FirstName @item.LastName</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-id="@ViewBag.Id">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestOrganization/Views/Employees/Index.cshtml
@model IEnumerable<TestOrganization.Models.Employee>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" asp-route-id="@ViewBag.Id">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Designation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReportsTo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Designation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReportsTo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
            <td>
                <a asp-controller="LeaveRequests" asp-action="Index" asp-route-id="@item.Id">Leave Request</a>
            </td>
        </tr>
}
    </tbody>
</table>